### ISSUE TITLE
Research Next.js Integration with Strapi

### ISSUE THREAD

**Issue by Brenosalv** [estuary/marketing-site#615]
## Description

- Explore how Next.js fetches content from Strapi with GraphQL.
- Evaluate tools like Apollo Client for GraphQL to leverage the current queries.
- Research processing/rehyping HTML and optimizing blog images.

## Work required

-   [ ] Document findings with clear recommendations for data fetching and how Next.js handle blog post HTML and image processing.

**Comment by travjenkins** [comment]
https://strapi.io/blog/build-a-blog-with-next-react-js-strapi

**Comment by Brenosalv** [comment]
I think it makes sense to switch from Less to Sass. Next.js has built-in support for Sass, which means easier configuration, better compatibility with the framework, and fewer dependencies to manage.

Sass also offers modern features like @use and @forward, which improve modularity and maintainability compared to Less. Additionally, Sass has a larger community and stronger long-term support, making it a more future-proof choice.

By migrating to Sass now, we align our styling approach with Next.js best practices, reduce potential technical debt, and simplify the project’s overall setup.

It's just few steps to convert LESS code to SASS since it's a bit similar, which won't cost us a long time.

**Comment by Brenosalv** [comment]
For fetching content from Strapi with Next.js, we’ve got two main options: **GraphQL** and **REST**. It’s just a matter of weighing the pros and cons.

### GraphQL:

Pro:
- Precision: GraphQL lets us query for exactly the data we need, minimizing over-fetching.

Con:
- Additional Dependency: To take full advantage of its capabilities—such as robust caching—we would need to integrate a third-party package like Apollo Client. This can increase our app’s bundle size.

### REST:

Pro:
- Built-In Simplicity: Using REST with Next.js’s built-in Fetch API allows us to retrieve content from Strapi without adding extra dependencies.

Con:
- Over-Fetching: The trade-off is that REST endpoints typically return fixed data structures, which means we might end up fetching more data than necessary as we can see below:

<img width="426" alt="Image" src="https://github.com/user-attachments/assets/b31d78b0-e0a0-449d-b2b3-5f53c117588a" />

**Comment by travjenkins** [comment]
We control Strapi though... so can't we control what the REST calls return on the Strapi side?

**Comment by travjenkins** [comment]
Missed this initially - sorry.

We should only be using Next.JS as a SSG so anything like Apollo Client could just be used to fetch it and I would hope Next.JS is smart enough to know to not include that since it is only using in a `getStaticProp` kind of call

**Comment by Brenosalv** [comment]
Yes, I’m using server components with SSG. Since Apollo Client is designed to be used in a client component, using REST requests with the native Fetch API seems like the best choice here.

I think it’s possible to control what the REST calls return on the Strapi side, but even if it’s not, I don’t think the unused data would have a big impact, as most of it consists of null values or simple texts. Anyway, I can check how to filter what we fetch specifically.

**Comment by travjenkins** [comment]
We also might be able to use all the unused data as part of a cache key to manage finding changes.

**Comment by Brenosalv** [comment]
We can filter which the fetched fields doing this:

<img width="424" alt="Image" src="https://github.com/user-attachments/assets/4148b092-313d-4496-8f71-984931f71f82" />

<img width="537" alt="Image" src="https://github.com/user-attachments/assets/058eb132-a1f1-43ff-ad52-d971ad196f8a" />

It's concatenating strings rather than a single template literal due to a much better readability.

**Comment by travjenkins** [comment]
Great! So it looks like something we could write a little helper to generate that string with or even look into using some `strapi client` that is readibly available.

But great news no matter what!

**Comment by Brenosalv** [comment]
I ran next build and the blog post pages are being pre-rendered using static site generation as expected:

<img width="1077" alt="Image" src="https://github.com/user-attachments/assets/f92f1bb4-937f-433b-a6ea-02debed70dac" />

**Comment by travjenkins** [comment]
Do you mean a subset of the blogs? Cause this is not enough paths for all of our blogs. This looks like the first chunk of pagination

![Image](https://github.com/user-attachments/assets/27d86eea-8195-4b9f-b8d7-edaa270b4482)

**Comment by Brenosalv** [comment]
Yes, we need to pre-render all the blog post pages with pagination. Until then, it's a total of 12 API requests with a total of 568 blog posts:

<img width="513" alt="Image" src="https://github.com/user-attachments/assets/1610a161-4b26-4c7d-810e-f74ca0afb380" />

<img width="406" alt="Image" src="https://github.com/user-attachments/assets/d55f5d40-f02c-4cc6-aed1-2fc2c40c77b5" />

**Comment by Brenosalv** [comment]
Below are the manipulations related to the HTML rehype:
- Blog post images are processed using the Next.js Image component.
- The images use the WEBP format and lazy loading.
- There is less DOM nesting, with no divs wrapping the img compared to Gatsby that has some parent divs.
- Removing the paragraph that wraps the img.
- The anchor wrapping img is preserved without need for DOM manipulation, unlike the approach with Gatsby.

<img width="1507" alt="Image" src="https://github.com/user-attachments/assets/f048e191-766d-48db-a39b-4095dd23c2d9" />

- Images are centralized:

<img width="912" alt="Image" src="https://github.com/user-attachments/assets/62ff893a-a23e-4f08-b590-03f295773db7" />

- The <br> from all the <li> also was removed since it's unused:

<img width="1137" alt="Image" src="https://github.com/user-attachments/assets/d276bcd5-6d1d-49ba-a9cd-63dbb843616d" />

- All anchors are replaced with next.js Link component while the external links are opening in a new tab:

<img width="1101" alt="Image" src="https://github.com/user-attachments/assets/2a0e8530-fc29-4f95-97c6-6ef6b2ec9b7e" />

All these changes are executed at build time on the server side.

Below is the build time, always cleaning cache before running a new build:
- NEXT_DEBUG_BUILD=true npm run build  57.65s user 6.74s system 230% cpu 27.931 total
- NEXT_DEBUG_BUILD=true npm run build  57.64s user 7.24s system 243% cpu 26.615 total
- NEXT_DEBUG_BUILD=true npm run build  57.64s user 6.82s system 221% cpu 29.132 total

We still need to process video, code and other type of content.

**Comment by travjenkins** [comment]
okay awesome.

Processing the `code` we might want to look into a different solution. The current one is forced to load the script multiple times (https://github.com/estuary/marketing-site/issues/405)

**Comment by Brenosalv** [comment]
With max supabase connections = 1, the result was:
- NEXT_DEBUG_BUILD=true npm run build  160.25s user 16.39s system 205% cpu 1:25.82 total

**Comment by Brenosalv** [comment]
The rest of the integration page sections are migrated and the new build time is:

NEXT_DEBUG_BUILD=true npm run build  188.79s user 17.16s system 292% cpu 1:10.36 total

The only fetching we are running is the `fetchAllConnectors`. The connectors data is cached in a map variable and reused in the sections so we don't need to make more than one request. It's working fine locally. An example is the related integrations section where we just reuse the cached connectors applying filters:

<img width="717" alt="Image" src="https://github.com/user-attachments/assets/6677a625-8372-4eff-8595-818447e7f6c6" />

**Comment by Brenosalv** [comment]
Just for the record... the content of all blog posts and connectors were fetched and listed to test scalability:

<img width="780" alt="Image" src="https://github.com/user-attachments/assets/18c5815e-420f-4a23-acdf-2cc4ddff2bae" />

**Comment by Brenosalv** [comment]
That's the result of the build with all the page components:

<img width="1150" alt="Image" src="https://github.com/user-attachments/assets/0bd1d039-e671-4391-81b2-f72e049358c4" />

Obs: It's missing the articles related to the integrations because the fetch was returning error `503: Service unavailable` for some integration pages and I'm still checking why it's happening.

**Comment by Brenosalv** [comment]
Next.js does not provide a built-in solution for this, but I worked on a solution.

We can store the fetched data in disk and reuse it. I did this for the connectors and the results look good. If you agree, we can do this with the blog post pages as well.

After implementing this, the first build took the time we already know, but the second build was very faster and the Supabase API request was only one even with two consecutive builds.

In this solution, we add an on-disk cache for the Supabase connector data in JSON format and reuse it in following builds. First, I created a `cache.ts` module that reads and writes `connectors.json` in a `.cache/` folder in the root of the project. I then updated `loadConnectorsCache()` to try loading from that file before querying the database, falling back and rewriting the cache only when it’s missing or expired.

After running the two consecutive builds, here are the results:
- Build 1: NEXT_DEBUG_BUILD=true npm run build  218.81s user 20.57s system 199% cpu 1:59.81 total
- Build 2: NEXT_DEBUG_BUILD=true npm run build  223.23s user 20.28s system 645% cpu 37.729 total

In other words:
- Build 1: fetched from DB, wrote disk cache, ~120s wall-clock;
- Build 2: hundreds of cache loaded connectors from disk cache, reused `.next/cache`, ~38s wall-clock.

It cut our local build time by ~70%. The remaining CPU work is still dominated by prerendering almost 7 000 pages in a pure SSG run, but the compilation and bundling phases now complete in seconds.

**Comment by travjenkins** [comment]
Sounds good. 

What did you use to generate the cache key?

Next try to think through how you'd want to handle `delta updates`. We should also cache off the date we last fetched each endpoint and check for only new items. We might not do this with connectors as it is a bit harder. However, strapi does have a `last updated` column we can use for this. That way we can just fetch what has changed and reduce the scope of the build.

**Comment by Brenosalv** [comment]
In the Github actions workflow we can generate our cache key with the built‐in hashFiles helper on our lockfile plus the runner OS, for example: `key: ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}`. That keeps our cache in sync with dependency and OS changes, but it won’t revalidate when new connectors are added in Supabase or new posts in Strapi as you know, which is what we need. But yeah, I think we can use delta updates to solve this.

To handle delta updates, we can drop in a tiny `metadata.json` next to our disk cache just like this:

```
// .cache/metadata.json
{
  "postsLastFetched": "2025-04-22T18:00:00.000Z",
  "connectorsLastFetched": "2025-04-22T18:00:00.000Z"
}
```

On each build we read those timestamps, call Strapi’s API like:
```
const resp = await fetch(
  `${process.env.STRAPI_API_URL}/api/blog-posts?filters[updatedAt][$gt]=${postsLastFetched}`
);
const newPosts = await resp.json();
```

And if we had or if we can add a column `updated_at` on Supabase, we would run a query such as:

```
SELECT * FROM connectors
 WHERE updated_at > $1;
```

We then merge any returned items into our existing `.cache/*.json`, update `postsLastFetched` and `connectorsLastFetched` to the latest `updatedAt` values, and write that back to `.cache/metadata.json`. This way we only fetch and rebuild what actually changed without ever touching the Github Actions cache key.

What do you think?

**Comment by travjenkins** [comment]
So that is a good cache key for the entire build. However, you are writing your own cached data to disk. So how are those keys created?

We'll also need a way to clear this cache when we need to. So we probably want to clear it during something like a `master` merge or something. That way we have _some_ cadence of when we flush the cache and do a full build. Since this cache is mainly just to make sure we don't have to hammer `strapi` all the time.

**Comment by Brenosalv** [comment]
We’re not generating any fancy hash keys inside our disk‐cache JSON, our keys are just the connector `slugified_name`. Here’s what happens when we load the cache:
```
// readConnectorCache() gives us back an array of StrapiConnector
const allConnectors = await readConnectorCache(); // e.g. [{ id: 1, title: "Postgres", … }, …]

// then we build our in-memory map:
const connectorsCache: Record<string, StrapiConnector> = {};
for (const conn of allConnectors) {
  const normalized = normalizeConnector(conn);
  // normalizeConnector creates a slug like "postgres-to-bigquery"
  if (normalized.slugified_name) {
    connectorsCache[normalized.slugified_name] = conn;
  }
}
```

About the cache updates with Strapi, we still can fire the Strapi webhook into GitHub’s `repository_dispatch` on every `create/update/delete/publish/unpublish`. We just need to wire those events into both cache flushes on `main` merges and per-item cache updates for deletes. Below are the two cases:

1. Flush the full disk cache on master merges:
In our CI workflow, we can detect both a normal push to `main` and a Strapi webhook driven dispatch, then nuke `.cache/` before the build. This guarantees we get a full refresh on every deploy to production:
```
on:
  push:
    branches: [main]
  repository_dispatch:
    types: [strapi_updated]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # If we’re on main (either via direct push or Strapi dispatch), clear the cache
      - name: Clear disk cache on main
        if: github.ref == 'refs/heads/main'
        run: rm -rf .cache
```

2. Handle single‐item deletes in the disk cache:
Here we can add a tiny CLI script that our workflow calls when the webhook says `event_type: delete`. It will read `.cache/connectors.json`, filter out the deleted slug, and write it back:
```
// scripts/cache-event.js
import fs from 'fs/promises'
import path from 'path'

async function main() {
  const [,, event, slug] = process.argv
  const file = path.resolve(process.cwd(), '.cache/connectors.json')
  let data = JSON.parse(await fs.readFile(file, 'utf-8'))

  if (event === 'delete') {
    data = data.filter(conn => conn.slugified_name !== slug)
    console.log(`[cache-event] removed "${slug}" from connectors.json`)
  }
  // you could add create/update logic here too…

  await fs.writeFile(file, JSON.stringify(data, null, 2))
}

main().catch(err=>{ console.error(err); process.exit(1) })
```

Then in our GitHub Actions:
```
on:
  repository_dispatch:
    types: [strapi_updated]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # parse the webhook payload
      - name: Apply cache event
        if: github.event.client_payload.event_type == 'delete'
        run: |
          npm ci
          node scripts/cache-event.js delete ${{ github.event.client_payload.slug }}

      # now continue with the normal build (which will load the updated .cache)
```

With this:
- Merges to `main` always blow away the entire cache and force a full fresh fetch.
- Per-item deletes prune exactly that connector from the cache without rebuilding everything.

We can extend `cache-event.js` script to handle create and update by fetching just that one slug and merging it in, or leave those to our delta-fetch logic.

Below is how would be our entire `deploy-prod.yml`:
```
name: Deploy Next.js SSG to Firebase Hosting

on:
  # 1) Every merge to main — triggers a full refresh of our disk‐cache
  push:
    branches:
      - main

  # 2) When Strapi emits our webhook (create/update/delete/publish/unpublish)
  repository_dispatch:
    types: [strapi_updated]

  # 3) Manual dispatch if needed
  workflow_dispatch:

  # 4) (Optional) Nightly rebuild at 01:00 UTC
  schedule:
    - cron: '0 1 * * *'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    concurrency:
      group: prod
      cancel-in-progress: true

    steps:
      # --- checkout & setup ------------------------------------------------
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      # --- cache-flush on main merges --------------------------------------
      - name: Clear disk cache on main
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/heads/main')
        run: rm -rf .cache

      # --- per-item delete handling via webhook ----------------------------
      - name: Prune deleted connector from cache
        if: >
          github.event_name == 'repository_dispatch' &&
          github.event.client_payload.event_type == 'delete'
        run: |
          npm ci
          node scripts/cache-event.js delete ${{ github.event.client_payload.slug }}

      # --- restore our GH Actions cache -----------------------------------
      - name: Restore cache
        id: cache
        uses: actions/cache@v4
        with:
          path: |
            node_modules
            .cache           # our on-disk JSON cache
            .next/cache      # Next.js’s own filesystem cache
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-nextjs-

      # --- install & verify ------------------------------------------------
      - name: Install dependencies
        run: npm ci

      - name: Lint & Type-check
        run: |
          npm run lint
          npm run type-check
        env:
          CI: true

      # --- build & export static HTML -------------------------------------
      - name: Build & Export Static HTML
        env:
          NEXT_PUBLIC_STRAPI_API_URL: ${{ secrets.STRAPI_API_URL }}
          STRAPI_TOKEN:               ${{ secrets.STRAPI_TOKEN }}
        run: |
          npm run build
          npm run export

      # --- deploy to Firebase ----------------------------------------------
      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken:              ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
          projectId:              estuary-marketing
          channelId:              live
          expires:                30d

      # --- optional: clean up stale caches --------------------------------
      - name: Clean up old caches
        if: ${{ always() }}
        run: |
          gh extension install actions/gh-actions-cache
          CACHE_KEYS=$(gh actions-cache list -R ${{ github.repository }} -B ${{ github.ref_name }} | cut -f 1)
          for key in $CACHE_KEYS; do
            if [[ "$key" != "${{ steps.cache.outputs.cache-hit }}" ]]; then
              gh actions-cache delete "$key" -R ${{ github.repository }} --confirm
            fi
          done
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```
